[foreign_chain]
rpc_url = "http://foreign-node:8545"
token_contract_address = "0xc59636130365C6723e760Dd55436BE54495c6133"
bridge_contract_address = "0x22bB53A8dC4EbeFE66451E0B65878afe8Aa13B29"
event_fetch_start_block_number = 1596703

[home_chain]
rpc_url = "http://home-node:8545"
bridge_contract_address = "0x7eEB97F2e1D3278813D4F134226346C722126Be3"
event_fetch_start_block_number = 4773371

[validator_private_key]
keystore_path = "/config/keys/Trustlines/account.json"
keystore_password_path = "/config/pass.pwd"
