# Base config file for openethereum

[parity]
base_path = "/home/openethereum/.local/share/openethereum"
chain = "/home/openethereum/.local/share/openethereum/trustlines-spec.json"
keys_path = "/home/openethereum/.local/share/openethereum/custom/keys"
db_path = "/home/openethereum/.local/share/openethereum/chains"

[misc]
# Prevent problems we had with invisible logs
color = false
